[workspace]
members = [
    "pepper",
    "plugin-lsp",
    "plugin-remedybg",
    "mine",
]
exclude = ["web"]
default-members = ["mine"]

[profile.release]
debug = true
incremental = true
lto = "off"

[profile.dev]
debug = true
incremental = true
lto = "off"

