[package]
name = "pepper-web"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
name = "pepper_web"
path = "src/lib.rs"

[dependencies]
pepper = { path = "../pepper" }
wasm-bindgen = "0.2"

